# terms in this list will be filtered
# note that all terms should be written without whitespaces for better filtering
profanity:
- asshole
- bastard
- bitch
- cunt
- fuck
- fucker
- motherfucker
- nigga
- sonofabitch
- sonofawhore
- slut
- whore
# chars in the same group will be treated as equal
# if a char is in more than one group it might cause unexpected behavior
charGroups:
- 0oö
- 1ily|!
- 258bszß§$&
- 3e€
- 4aä@
- 6g
- 7dt+
- uüv
- mn
- vw
- x%
- ck([{<
- )]}>
# sequences in the same group will be treated as equal
# sequences are separated with a semicolon
# important note: the order here is relevant as all sequences are only applied once
# so if you want one sequence to affect parts of another it must come after that
sequenceGroups:
- ä;ae
- ai;ei
- ak;awk;ok;owk
- ass;arse
- b;i3
- bait;bate;b8
- d;c|;|)
- ga;gar;ger;gur
- h;|-|
- i;ie
- ka;kar;ker;kur
- lait;late;l8
- w;\n
- m;|v|;|v\;/v\;/v|
- n;/v;|v
- o;()
- ö;oe
- x;chs;ks;)(
- sh;sch
- st;scht
- sp;schp
- ta;tar;ter;tur
- ü;ue
- v;\/;|/;\|
- wo;who